### ISSUE TITLE
Kanban board

### ISSUE THREAD

**Issue by danielamoreno699** [danielamoreno699/WanderPal#7]
**Links to the repositories:**

https://github.com/users/danielamoreno699/projects/1
https://github.com/danielamoreno699/WanderPal ( Backend)
https://github.com/danielamoreno699/wanderpal-frontend (Frontend)

**number of team members:** 4

![kanbanscreenshot](https://github.com/danielamoreno699/WanderPal/assets/68881261/8b19a7e6-7fce-4bf2-bf03-034342a04e18)

**Comment by Meltrust** [comment]
Hi @danielamoreno699,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, have been assigned, and are pointed fairly according to the requirement✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
